### PR TITLE
sy/update/footer

### LINKED ISSUE #88: Centre footer in mobile View
The footer content needs to be centered and justified. the social buttons and "Created By GCSRM Team 🐐" needs to be centered.
Also center the logo and adderss

Screenshot 2024-10-18 at 11 35 01 PM

### PR DESCRIPTION
**Pull request by Sameer01-01**
updated and centered footer and hidden the scroll button for the footer section.

### footer view in mobile

Screenshot 2024-10-23 162730

the scroll up button  will appear in its place when you are in the contact us section.

Screenshot 2024-10-23 162744

### CODE REVIEW

**Comment by djdiptayan1** [comment]
Screenshot 2024-10-24 at 12 24 52 AM

Try to keep this left aligned in desktop mode.

**Comment by UtkarshJaiswal1406** [comment]
A lot of awkward spacing here. Fix this

MvY5JBVBPF

**Comment by Sameer01-01** [comment]
> A lot of awkward spacing here. Fix this
> 
> MvY5JBVBPF

I have reduced the spacing and aligned the text for the desktop to the left. I haven't changed it for the mobile display.

Screenshot 2024-10-24 115800

**Review by djdiptayan1 — APPROVED** [review]
LGTM

**Review by UtkarshJaiswal1406 — APPROVED** [review]
lgtm

**Pull request merged**
