### PR TITLE
#83 has been fixed

### LINKED ISSUE #83: Incorrect span of hero section on home page
## The hero section isn't spanning the entire page
The home screen should be completely covered by the hero section. The About Us box should only be visible after scrolling down a bit instead of popping up awkwardly at first load. Please fix it

chrome_sLlBWHVPeB

### PR DESCRIPTION
**Pull request by sahaj24**

### CODE REVIEW

**Comment by UtkarshJaiswal1406** [comment]
Not fixed

chrome_WdZ6teU0g3

**Review by sahaj24 — COMMENTED** [review]
Update

**Comment by UtkarshJaiswal1406** [comment]
> Update

Yeah Im looking at the deployment done AFTER your changes. it isnt fixed

**Comment by djdiptayan1** [comment]
Put h:[100vh] in the hero component. It will probably be fixed

**Comment by djdiptayan1** [comment]
Screenshot 2024-10-24 at 11 41 02 AM

Try what I suggested in Hero.jsx file Components -> Home -> Hero.jsx

**Review by UtkarshJaiswal1406 — APPROVED** [review]
lgtm

**Review by UtkarshJaiswal1406 — CHANGES_REQUESTED** [review]
looking weird on 1800x1169 (default mac screen)

use vh. itll adapt to the screen size

**Comment by sahaj24** [comment]
I have corrected it  . Will upload shortly

**Review by djdiptayan1 — APPROVED** [review]
LGTM

**Review by UtkarshJaiswal1406 — APPROVED** [review]
lgtm

**Pull request merged**
