### PR TITLE
removed the recruitment section from the website along with the code elements and images

### LINKED ISSUE #85: Recruitment section still visible
Since the recruitments are over for this year, this section should be cleanly removed from the website along with its elements (for eg, the navbar entry). Please fix

chrome_4jBKa3nyDA

### PR DESCRIPTION
**Pull request by Sameer01-01**
## Website

Screenshot 2024-11-02 142016

## File Structure after removal

Screenshot 2024-11-02 141737

### CODE REVIEW

**Comment by djdiptayan1** [comment]
Dont delete the components, just delete the pages and link from navbar.

**Comment by UtkarshJaiswal1406** [comment]
can you shift the right side navbar elements more towards the right? 
that space over there looks awkward

**Comment by Sameer01-01** [comment]
> Dont delete the components, just delete the pages and link from navbar.

I've restored the recruitment components
Screenshot 2024-11-02 181228

**Comment by Sameer01-01** [comment]
> can you shift the right side navbar elements more towards the right? that space over there looks awkward

Shifted the navbar elements to a little bit right to reduce spacing

Screenshot 2024-11-02 181617

**Review by UtkarshJaiswal1406 — APPROVED** [review]
lgtm

**Review by djdiptayan1 — APPROVED** [review]
LGTM

**Review by StarlyHere — APPROVED** [review]

**Pull request merged**
